name: Arch AUR Repository Push

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      
      options: --privileged
      
      env:
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.4.0
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Make PKGBUILD and .SRCINFO
      run: |
        pacman -Syu --noconfirm
        pacman -S --needed git curl jq base-devel --noconfirm
        git config --global user.name "${GIT_NAME}"
        git config --global user.email "${GIT_EMAIL}"
        git clone https://github.com/NSK-1010/floorp-mirror.git
        cd floorp-mirror
        bash push.bash
        makepkg --printsrcinfo > .SRCINFO
        git add -A
        git commit -m "v$(cat PKGBUILD | grep 'pkgver=' | sed s/pkgver=//)-$(cat PKGBUILD | grep 'pkgrel=' | sed s/pkgrel=//)"
        git push origin main
